### ISSUE TITLE
Upgrade to rc.4?

### ISSUE THREAD

**Issue by Dutchboy** [flaviait/ng2-jspm-template#14]
Hi all,

Can you please upgrade to rc4????

Thanks so much,

Lars

**Comment by sv2dev** [comment]
@Dutchboy Thanks, I didn't notice that rc4 is out.
I'll update as soon as I've got time :-)

**Comment by DorianGrey** [comment]
@svi3c I've attempted to start the update on the rc4-updates branch (incl. several dependency updates, or course). However, it fires up several errors, w.r.t. to `process-styles` and typings resolution that appear rather ... curious (same goes to jspm behavior, but that's a different story). Maybe you've got an idea how to fix these.

**Comment by DorianGrey** [comment]
Fixed by https://github.com/flaviait/ng2-jspm-template/pull/15 .
