### ISSUE TITLE
Improve output formatting

### ISSUE THREAD

**Issue by DorianGrey** [flaviait/ng2-jspm-template#27]
Now that we're running an increasing number of tasks in parallel, we should consider to format their output, and maybe colorize it as well (we already have a transitive dependency on [chalk](https://github.com/chalk/chalk)). Especially the linter outputs are very discreet atm. 

@svi3c, any thoughts / wishes / preferences?

**Comment by sv2dev** [comment]
Yes, chalk would be nice, I think.
